
version: '2.2'

services:

  starter_client:
    build:
      context: test_client
    user: nobody
    image: cyberdojo/starter-client
    init: true
    container_name: test-starter-client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - custom
      - exercises
      - languages
    restart: 'no'
    ports:
      - 4528:4528

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter:
    user: nobody
    image: cyberdojo/start-points-test
    init: true
    container_name: test-starter-server
    volumes:
      - ./test_server:/app/test:ro
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports:
      - 4527:4527


  custom:
    user: nobody
    image: cyberdojo/start-points-custom
    init: true
    container_name: test-custom-server
    volumes:
      - ./test_server:/app/test:ro
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports:
      - 4527:4527

  exercises:
    user: nobody
    image: cyberdojo/start-points-exercises
    init: true
    container_name: test-exercises-server
    volumes:
      - ./test_server:/app/test:ro
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports:
      - 4526:4526

  languages:
    user: nobody
    image: cyberdojo/start-points-languages
    init: true
    container_name: test-languages-server
    volumes:
      - ./test_server:/app/test:ro
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports:
      - 4525:4525
