version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build start-points-base docker image and push image to docker hub
          command: |
            set -ev
            #./pipe_build_up_test.sh
            ./sh/build_base_docker_image.sh
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
            # NB: latest is tag used in the FROM inside the Dockerfile inside the main script
            # build_cyber_dojo_start_points_image.sh and so must be pushed.
            docker push cyberdojo/${project}:latest
      - run:
          name: machine-user triggering start-points-languages
          command: |
            set -ev
            ./sh/trigger_start_points_languages.sh

workflows:
  version: 2
  build-publish:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
