version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build start-points-base docker image and push image to docker hub
          command: |
            set -ev
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            #./pipe_build_up_test.sh
            ./sh/build_base_docker_image.sh
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
            # NB: latest is tag used in the FROM inside the Dockerfile inside the main script
            # build_cyber_dojo_start_points_image.sh and so must be pushed.
            docker push cyberdojo/${project}:latest
            #curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/start-points-languages/build?circle-token=${CIRCLECI_BUILD_TOKEN}
      - add_ssh_keys:
          fingerprints:
            - "59:27:44:af:db:b9:c2:a6:a2:5b:83:fc:d4:a4:c4:59"
      - run:
          name: machine-user triggering start-points-languages
          command: |
            set -ev
            ./sh/trigger_start_points_languages.sh

workflows:
  version: 2
  build-publish:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
