version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build start-points-base docker image and push image to docker hub
          command: |
            set -ev
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            ./pipe_build_up_test.sh
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
            docker push cyberdojo/${project}:latest
            curl --fail -X POST https://circleci.com/api/v1.1/project/github/cyber-dojo/start-points-languages/build?circle-token=${CIRCLECI_BUILD_TOKEN}

workflows:
  version: 2
  build-publish:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
