version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: push tagged docker image to dockerhub
          command: |
            set -ev
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
            # NB: latest is the tag used in the FROM inside the Dockerfile
            #     (in the main script cyber_dojo_start_points_create.sh)
            #     and so must be pushed.
            docker push cyberdojo/${project}:latest
      - run:
          name: trigger start-points-languages
          command: |
            set -ev
            ./sh/trigger_start_points_languages.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
