version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: publish tagged docker image to dockerhub
          command: |
            set -ev
            readonly image=cyberdojo/starter-base
            docker tag  ${image}:latest ${image}:${CIRCLE_SHA1:0:7}
            docker tag  ${image}:latest ${image}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push ${image}:${CIRCLE_SHA1:0:7}
            docker push ${image}:beta
            # NB: latest is the tag used in the FROM inside the Dockerfile
            #     (in the main cyber-dojo script) and so must be pushed.
            docker push ${image}:latest
      - run:
          name: trigger dependent repos
          command: |
            set -ev
            ./sh/trigger.sh custom
            ./sh/trigger.sh exercises
            ./sh/trigger.sh languages

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
